### ISSUE TITLE
please grammar check and reword report.rmd

### ISSUE THREAD

**Issue by tobiasuruali** [UniLuFS2020-ReplicationSeminar/Data_Mining_EX1#1]
@patrick-stoeckli Please help rewrite and grammar check the first section of "report.rmd". I'm not good at the english

**Comment by patrick-stoeckli** [comment]
@tobiasuruali sry for my rather late answer. but no worries: i will have time to help tomorrow for sure!

**Comment by patrick-stoeckli** [comment]
i just reworded and shortened the report.
