### ISSUE TITLE
missing family name and students numbers.

### ISSUE THREAD

**Issue by patrick-stoeckli** [UniLuFS2020-ReplicationSeminar/Data_Mining_EX1#3]
hi @micopa and @tobiasuruali 

i realised that your family name is missing in the report.Rmd file, Miguel! please add it, i can't remember :)

i also think we should include our student-numbers :)

**Comment by patrick-stoeckli** [comment]
i just realized that your name is on github, @micopa. so i do not need that anymore.

however, i still think we should add our student-numbers :)

**Comment by micopa** [comment]
Added my student number
